"""Requisitos del sistema y las pruebas que los verifican (trazabilidad)."""

REQUISITOS = [
    ("RF-01", "Consultar el catálogo de letreros luminosos", "funcional",
     ["test_listar_tipos_devuelve_tres", "test_obtener_tipo_inexistente_falla",
      "test_comparar_incluye_ambos_tipos"]),
    ("RF-02", "Cotizar un letrero según tipo, medidas, RGB e instalación", "funcional",
     ["test_cotizar_neon_basico", "test_cotizar_con_rgb_e_instalacion",
      "test_area_minima_facturable"]),
    ("RF-03", "Validar que las medidas sean numéricas y estén en rango", "funcional",
     ["test_medida_fuera_de_rango", "test_medida_no_numerica"]),
    ("RF-04", "Calcular el IVA (16%) y el total de la cotización", "funcional",
     ["test_iva_16_por_ciento"]),
    ("RF-05", "Registrar pedidos con descuento por volumen", "funcional",
     ["test_descuento_5", "test_descuento_10", "test_registrar_pedido_persiste",
      "test_cliente_obligatorio"]),
    ("RF-06", "Controlar el estado del pedido (flujo válido)", "funcional",
     ["test_transicion_valida", "test_transicion_invalida", "test_cancelado_no_suma_al_total"]),
    ("RF-07", "El asistente IA cotiza a partir de texto libre", "funcional",
     ["test_soporte_cotiza_desde_texto", "test_soporte_pide_medidas_si_faltan"]),
    ("RF-08", "El asistente IA diagnostica fallas y crea tickets", "funcional",
     ["test_soporte_falla_crea_ticket", "test_soporte_riesgo_electrico_es_alta",
      "test_soporte_responde_catalogo", "test_soporte_mensaje_otro"]),
    ("RF-09", "Registrar el tiempo de resolución de cada ticket", "funcional",
     ["test_resolver_ticket_calcula_tiempo", "test_resolver_ticket_invalido"]),
    ("RNF-01", "Fiabilidad: tolerar la falla del proveedor de IA", "fiabilidad",
     ["test_soporte_tolera_fallo_proveedor", "test_soporte_usa_proveedor_ia",
      "test_gemini_redacta_y_cuenta_llamadas", "test_gemini_tolera_fallo_de_red",
      "test_crear_proveedor_segun_variables"]),
    ("RNF-02", "Recuperabilidad: recuperarse de archivos de datos dañados", "fiabilidad",
     ["test_repositorio_recupera_archivo_corrupto", "test_agregar_y_cargar",
      "test_actualizar_inexistente"]),
]
